Dockerfile
autometa.py
autometa/binning/recursive_dbscan.py
autometa/common/coverage.py
autometa/common/external/bedtools.py
autometa/common/external/bowtie.py
autometa/common/external/diamond.py
autometa/common/external/hmmer.py
autometa/common/external/prodigal.py
autometa/common/external/samtools.py
autometa/common/external/work_queue.py
autometa/common/kmers.py
autometa/common/mag.py
autometa/common/markers.py
autometa/common/metagenome.py
autometa/common/utilities.py
autometa/config/__init__.py
autometa/config/databases.py
autometa/config/default.config
autometa/config/environ.py
autometa/config/metagenome.config
autometa/config/project.py
autometa/config/user.py
autometa/taxonomy/lca.py
autometa/taxonomy/majority_vote.py
autometa/taxonomy/ncbi.py
docs/template.py

resolved #10 Contributors added and copyright year updated to 2020.

---

pipeline/ML_recruitment.py
pipeline/ML_recruitment_docker.py
pipeline/add_contig_taxonomy.py
pipeline/calculate_read_coverage.py
pipeline/calculate_read_coverage_docker.py
pipeline/cluster_process.py
pipeline/cluster_process_docker.py
pipeline/cluster_taxonomy.py
pipeline/cut_long_contigs.py
pipeline/lca.py
pipeline/make_contig_table.py
pipeline/make_marker_table.py
pipeline/make_taxonomy_table.py
pipeline/make_taxonomy_table_docker.py
pipeline/recursive_dbscan.py
pipeline/run_autometa.py
pipeline/run_autometa_docker.py
pipeline/split_unclustered_contigs.py
pipeline/vizualize_assembly_graph_by_bin.py

resolved #27  This should resolve the errors arising from the difference in the version of python being used by the compiler and the interpreter.

resolved #27 removed the 2.7 from the shebang of all the python scripts in the pipeline directory.

---

pipeline/make_taxonomy_table.py

Added missing merged.dmp in database checking when using default autometa databases directory

Added missing merged.dmp in database checking

---

autometa/common/markers.py

* :art::green_heart: Add argparse formatter_class to show defaults without requiring f-strings. Helps doc builds from PR-#45 and issue-#22
* fixes #44

Add Markers class documentation.

---

autometa/__main__.py

resolves #60 
* :art: Rename --debug to --verbose flag
* :art: functionality to increase verbosity with additional -v flags
* :memo: Add docstrings to entrypoint and main functions

Add __main__.py documentation (fixes #60)

---

autometa/taxonomy/lca.py

- Fixes issue-#41
- :bug: Fix where writing is not reset when counts reached.

Fix writing

---

Dockerfile
LCA_README.md
README.md

Swap URLs to the new repo location

Change the URLs to github from bitbucket

---

pipeline/cluster_taxonomy.py

Resolves #93 
:bug: Fix taxid parsing bug.

Fix taxid parsing

---

pipeline/make_taxonomy_table.py

:art: Add python 3 compatibility for urllib and print statements.
:art: change `update_databases(...)` to `prepare_databases(...)` and add arg for explicitly updating
:art: Applied black formatting.

Add support for keeping outdated databases (updating requires explicitly using `--update` flag)

---

Dockerfile
requirements.txt

- :art::bug::green_heart::penguin: Fix Dockerfile. Now capable of running autometa entrypoints within docker container
- Fixes issue #3

Fix Dockerfile

---

autometa/common/coverage.py

:art: resolves KwanLab/Autometa/issue#125

Add support for gzipped assemblies

---

autometa/common/kmers.py
tests/unit_tests/test_kmers.py

- Resolves issue #124 
- :art: Add argument defaults formatter class to argparse ArgumentParser

Remove --multiprocess from autometa-kmers entrypoint

---

Dockerfile

Fix failing docker build
TODO:  #191

🐳:bug: Docker fix :whale:

---

docs/source/conf.py
docs/source/contribution-guidelines.rst
docs/source/index.rst

:memo: change links in contributing-guidelines.rst
:memo: Change source index from developer API to Autometa modules

:memo: Update Documentation

---

autometa/common/metagenome.py

:art::bug: Check whether output directory exists (and make if it doesn't) prior to writing length-filtered fasta file

:snake::art::bug: Update metagenome.length_filter(...)

---

CITATION.cff

Add CITATION file (#242)

---

.github/CONTRIBUTING.md
docs/source/bash-workflow.rst
docs/source/installation.rst
docs/source/legacy-autometa.rst

:memo: Update conda installation instructions for bash workflow
:memo: Minor formatting edits in docs/installation.rst

:memo: Update installation directions for bash workflow

---

modules/local/diamond_blastp.nf

:arrow_up: :green_apple: Upgrade Diamond 2.0.9 -> 2.0.14

---

autometa-env.yml

Fix for conda dependencies due to scikit-bio not being updated to use scipy 1.9
https://github.com/KwanLab/Autometa/issues/285

force scipy==1.8

---

autometa/validation/datasets.py

helpful error message added

---

workflows/autometa-large-data-mode.sh
workflows/autometa.sh

Implement changes by @Sidduppal in issue https://github.com/KwanLab/Autometa/pull/329#issuecomment-1594996732

:bug::shell: Fix GTDB taxon-binning workflow

---

docs/source/autometa-python-api.rst
docs/source/bash-step-by-step-tutorial.rst
docs/source/index.rst
docs/source/step-by-step-tutorial.rst

Resubmitting documentation update following https://github.com/KwanLab/Autometa/pull/278 to dev with updated docs

📝 Update documentation

---

autometa/taxonomy/database.py
autometa/taxonomy/vote.py

* :art::snake: fixes #305 
* :art::snake: Add `UNCLASSIFIED` attribute to `TaxonomyDatabase` class
* :art::bug::snake: Add logic to include blastp unaligned contigs to unclassified fasta

:bug::art::snake: Refactor 'unclassified' handling
