pipeline/add_contig_taxonomy.py, pipeline/make_taxonomy_table.py
This issue has since been resolved in the refactored version. This is a hotfix to master.
The error occurs when the `nr.dmnd` database search and `prot.accession2taxid.gz` recovers taxids different from the tree structure within nodes.dmp. This is easily resolved as NCBI has similarly provided a `merged.dmp` file with the old to new taxid translations.
```python
taxid = merged.get(taxid,taxid)
```
=> merge nodes when databases out of sync.

pipeline/make_taxonomy_table.py
- Found an issue with `check_dbs` where autometa will loook for `nr.dmnd.md5` and if it is not found, will update nr. However, when nr is updated, the nr.dmnd.md5 is never written. 
- Fixed file path handling to be less arch specific 
- updated variables for readability.
=> nr.gz database downloading bug

autometa/common/coverage.py
Bug found within logger message within function where `args` was being passed instead of records. (Thanks @samche42)
=> 🐛found in coverage

autometa/config/__init__.py, autometa/config/metagenome.config, autometa/config/user.py
- :art: Change f-string defaults in argparse parser to use `argparse.ArgumentDefaultsHelpFormatter`
- :art::memo: Add parameter do_taxonomy to metagenome.config
- :art: MAG class now imported in user.py for binning without taxonomy.
- :art::memo: resolves issue-#57
- :art::memo: resolves issue-#58
Note: Add COMBAK comments where checksum functionality should be added. This should be implemented in utilities.py and imported from there.
=> Add functionality to bin without taxonomy. Update docstrings

autometa/common/markers.py
- :art: Update logger format to reflect template.
- :bug: Removed lines generated from GUI merge conflict resolution.
- fixes #68 
- update to resolve bug from merge in #45
=> Remove merge conflict resolution lines (Fixes #68)

autometa/common/external/hmmer.py, autometa/config/environ.py
- :art: :racehorse: Replaced dispatcher dict by `globals()` [See](https://docs.python.org/3/library/functions.html#globals)
- :art: Changed the location of the checking `TypeError` in `getversions()` function
- :art: :fire: Suggestion: Current code to check if a program is in a the `$PATH` and is executable, is
```python
def which(program):
def is_exe(fpath):
return os.path.isfile(fpath) and os.access(fpath, os.X_OK)
fpath, __ = os.path.split(program)
if fpath:
if is_exe(program):
return program
else:
for path in os.environ["PATH"].split(os.pathsep):
exe_file = os.path.join(path, program)
if is_exe(exe_file):
return exe_file
return ''
``` 
We can use `shutil.which()` instead, which is concise and removes unneccesary code. [See](https://docs.python.org/3/library/shutil.html#shutil.which). …
=> :art: :racehorse: Resolves #55

autometa/common/external/hmmer.py, autometa/common/external/prodigal.py
- Resolve issue-#88
- :fire: Remove `--verbose` flags.
- :fire: Remove `--log` flag from hmmer.py
- :art: Change `prodigal.run` and `hmmer.hmmscan` to annotate with respective funcs parallel and sequential.
- :art: Aggregation of ORFs in prodigal performed with new `aggregrate_orfs` func.
=> verbose bug

autometa/binning/recursive_dbscan.py, autometa/common/exceptions.py, autometa/config/user.py
* resolves #52 
* :memo: Update docstrings
* :bug::racehorse:Update median completeness calculation to not incorporate all contigs but rather just cluster values.
* :art: Change `RecursiveDBSCANError` exception to `BinningError`
* :bug: Update `metabin` import in `user.py` from `mag.py`
* :art::fire: Remove default 'z' column in `run_dbscan` function and `usecols` parameters.
* :art: `add_metrics` func now returns 2-tuple with cluster_metrics dataframe for median completeness lookup.
* :art: Change default domain marker count lookup in `add_metrics` to raise error if domain does not match.
=> Recursive DBSCAN

autometa/binning/recursive_dbscan.py
:art: Add taxonomy specific splitting control
:art::racehorse: Add reverse-ranks parameter
:art::racehorse: Add starting-rank parameter
=> Rank-specific binning

pipeline/recursive_dbscan.py
:bug: handle case where all contigs are clustered in first DBSCAN round causing an empty table to be passed to DBSCAN resulting in a ValueError. (Thank you @cfrancoeur for bringing this to our attention)
:art: changed index length lookup for checking if the contig table is empty to the more readable syntax `table.empty`
=> Recursive DBSCAN ValueError from passing in empty unclustered contigs table

Dockerfile
After cloning the Autometa GH repo, navigating to Autometa fails.
🐛 Change `cd autometa/pipeline` to `cd Autometa/pipeline`
🎨 `MAINTAINER` is now deprecated and docker recommends using `LABEL` with the maintainer as the key in the key-value pair
=> Dockerfile path bugfix

autometa/binning/recursive_dbscan.py, autometa/binning/summary.py, autometa/common/metabin.py, autometa/common/metagenome.py, autometa/config/__init__.py, autometa/config/default.config, autometa/config/metagenome.config, autometa/config/user.py, autometa/taxonomy/ncbi.py, autometa/validation/cluster_taxonomy.py
Script to summarize MetaBins from autometa binning and taxonomy assignment (Takes as input autometa 2.0 file formats)
* :art: Update recursive_dbscan.py add_metrics func markers lookup methods for readability
* :art: Update default.config for both bacteria and archaea binning
* :art: Update user.py run_binning method for both bacteria and archaea file handling
* :art: Add fragmentation_metric method to MetaBin class
=> Binning stats/taxonomy summary

autometa/binning/unclustered_recruitment.py
Naive implementation of decision tree classifier and random forest without using KFolds cross validation.
- fixes #61 
- :art: Follows previous implementation of confidence metric calculations.
- 🐎  speed up on runtimes and filtering
- :art::memo: functions and docstrings available for increased reability/reusability.
- :art: Add parameter `--taxa-dimensions` for user (PCA dimensions for taxa one-hot encoding).
- :art: Add parameter `--kmer-dimensions` (PCA dimensions for normalized k-mer frequencies).
- :art: Add parameter `--additional-annotations` if user has custom table to include in training classifier for recruitment.
- :art: Add `--seed` parameter to set numpy `RandomState` for determinism.
=> decision tree classifier

autometa/binning/summary.py, autometa/config/__init__.py, autometa/config/project.py, autometa/config/user.py
:bug: save project config after adding metagenome to project dir
:memo: Update project docstring
=> Update project docstrings

pipeline/cluster_process.py
Changed "completness" to "completeness". This allows the edge case to actually be protected.
=> Fix typo on line 186 in cluster_process.py 

pipeline/run_autometa.py
This fix is one in a step to supporting global system install on HPCC with read-only access to marker folder
=> only try to generate hmm indexes if they do not exist

.readthedocs.yaml, docs/requirements.txt, modules/local/diamond_blastp.nf, nextflow.config
=> :fire::green_apple: Remove duplicate standard slurm profiles

autometa/common/coverage.py, autometa/common/external/bedtools.py, modules/local/parse_bed.nf, setup.py, tests/unit_tests/test_coverage.py
- 🐍 :fire: Remove deprecated argument bedtools genomecov command
- :snake::green_apple: Rename entrypoint for clarity: `autometa-parse-bed` -> `autometa-bedtools-genomecov`
- 🍏 🎨 Update `parse_bed.nf` with updated autometa entrypoint
- :snake::fire::white_check_mark: Remove unneeded param in `test_coverage.py`
- :snake::fire: remove unneeded `make_length_table(...)` from `coverage.py`
=> Fix bedtools genomecov deprecation (coverage calculation)

docs/source/running-autometa.rst
Adds the basic steps on how to run Autometa using nextflow. Still a work in progress on more advanced configs.
Basic steps won't work unless https://github.com/KwanLab/Autometa/pull/181 is merged (or when dev is eventually merged)
=> Nextflow documentation

autometa/validation/benchmark.py, docs/source/benchmarking.rst
:fire::memo: Reformat benchmarking docs according to @chasemc comments at https://github.com/KwanLab/Autometa/pull/189#issuecomment-933453441
=> :fire::memo: Reformat benchmarking docs

subworkflows/local/taxon_assignment.nf
if `params.large_downloads_permission = false` and nr.gz existed but nr.dmnd didnlt the pipeline would fail.
This...
// check for nr.dmnd, if not found, check for nr.gz
// if nr.gz exists, create nr.dmnd
// if nr.gz also doesn't exist, stop the pipeline
=> Add check for nr.dmnd and nr.gz

autometa/binning/recursive_dbscan.py, autometa/common/markers.py, modules/local/embed_kmers.nf, modules/local/markers.nf, subworkflows/local/lca.nf, tests/unit_tests/test_recursive_dbscan.py
Add error handling strategies for nextflow processes
1. embed_kmers.nf
- errorStrategy {exitCode in 153 ? "ignore" : "terminate" }
- Not enough contigs to perform embedding with current parameter settings
2. binning.nf
- errorStrategy { task.exitStatus in 204 ? 'ignore' : 'terminate' }
- No markers were annotated for contigs in the table
3. unclustered_recruitment.nf
- errorStrategy { task.exitStatus in 204 ? 'ignore' : 'terminate' }
- No markers were annotated for contigs in the table
4. markers.nf
- errorStrategy { task.exitStatus in 204 ? 'ignore' : 'terminate' }
- No markers in `kingdom.hmmscan.tsv` pass cutoff thresholds
=> Add error handling strategies for nextflow processes

.github/workflows/docker_autometa.yml, README.md, docs/source/nextflow-workflow.rst, nextflow-env.yml
:whale::green_heart: Dynamically tags `jasonkwan/autometa:tag` where `tag` is updated with a list of tags:
- :whale::green_heart: default branch is tagged with `latest`
- :whale::green_heart:  `dev` and `main` branches are tagged with their branch name
- :whale::green_heart:  releases are tagged with their release value, i.e. `2.0.0` is `jasonkwan/autometa:2.0.0`
- :memo::crab::green_apple: Added an `attention` block under Using `nf-core` section as nf-core may fail
when trying to use a local copy of a revision for the `KwanLab/Autometa` project that is not in sync with the GitHub revision
=> GH action: Add dynamic docker tags

autometa/common/external/bedtools.py
:bug::fire: Fix coverage calculation bug where lengths of contigs did not match when portion of the contig had 0 depth 
Fixes #239 
Thanks to @chtsai0105 for finding and pointing this out!
=> :bug::fire: Fix bedtools coverage calculation bug

autometa/taxonomy/lca.py
=> :bug: Fix the NoneType error during initating the LCA object (#246)

bin/check_samplesheet.py
fixes #249 
`utf-8-sig` codec should properly handle both utf-8 and utf-8-sig
https://peps.python.org/pep-0393/
=> allow utf-8-sig sample sheet files

autometa/binning/recursive_dbscan.py
- :snake: Add exit status code of `sys.exit(204)` for `BinningError('no clusters recovered')` in `autometa-binning`
- :snake::memo: Add extra warnings when this error is reached (i.e. Mentions as to why no clusters may have been recovered from this dataset and for the user to inspect their inputs).
- :green_apple::bug: Previously if no clusters were recovered from a particular dataset, the entire workflow would terminate, even though this dataset should just be ignored for downstream processes.
- :green_apple: `binning.nf` module already ignores `204` exit status as this is 'no content', continuing with the other input datasets but ignoring this for downstream processes.
=> :green_apple::snake::art: add exit status code of 204 for raised BinningError

autometa/validation/benchmark.py
:art::snake: Some taxon-profilers assign unclassified contigs to a taxid of 0 where others assign root taxid of 1.
The NCBI class method of converting the taxid datatype expects a positive integer, so we are converting the unclassified taxid of 0 to the root taxid of 1. All input predictions will be converted in this same way. The contigs with their converted taxids as well as the number of 'unclassified' taxids are now emitted in the logs during conversion.
=> :art::bug::snake: Convert 'unclassified' taxids of 0 to root taxid of 1

autometa/common/metagenome.py
When using the `autometa-length-filter` entrypoint, if `--output-fasta` is not specified with `./metagenome.filtered.fna` (or to a separate directory), e.g. `autometa-length-filter ... --output-fasta metagenome.filtered.fna` a `FileNotFoundError` will occur. Getting the absolute path of the output specified prior to checking the output directory of the output specified will prevent this error.
```bash
(autometa) evan@userserver:~/Autometa$ autometa-length-filter --assembly tests/data/78.125Mbp.fna.gz --output-fasta test.fna --output-gc-content test.gc_content.tsv 
[04/05/2022 02:04:35 PM INFO] autometa.common.metagenome: Getting contigs greater than or equal to 3,000 bp
Traceback (most recent call last):
File "/home/evan/miniconda3/envs/autometa/bin/autometa-length-filter", line 33, in …
```
=> :art::bug::snake: Fix `autometa-length-filter` bug when `--output-fasta` is specified without an output directory

autometa/taxonomy/ncbi.py
:snake::bug: delnodes.dmp taxids were parsed and added to the `self.delnodes` set. However these taxids were not converted to integers prior to being stored within the set, causing a check of a current taxid (an integer) to return `False` due to the taxid's string representation being stored.
=> :snake::bug: Fix parsing taxids to delnodes set

.github/workflows/pytest_codecov.yml, .pre-commit-config.yaml, Dockerfile, MANIFEST.in, Makefile, autometa/__init__.py, autometa/__main__.py, autometa/common/kmers.py, autometa/common/utilities.py, autometa/taxonomy/lca.py, bin/check_samplesheet.py, setup.py, tests/environment.yml, tests/unit_tests/test_kmers.py, tests/unit_tests/test_main.py
* 📝🎨🐍 Add `autometa` entrypoint (prints `--version`, `--citation`, or w/o args; commands with urls to docs and code)
* 🎨⬆️ pin black to version 22.3.0 for `.pre-commit-config.yaml` hooks and within `test/environment.yml`
* :bug::arrow_up: Previous black version was causing failures during pre-commit hook formatting. Upgrading to v22.3.0 resolves this issue
* 🐳 Add `autometa --version` when checking entrypoints in Dockerfile
One may test the `autometa` entrypoint by issuing the following commands:
```bash
git clone -b versioning https://github.com/KwanLab/Autometa
cd Autometa
make create_environment
conda activate autometa
make install
```
```bash
autometa
```
```bash
autometa --version
autometa -V
```
```bash
autometa --citation
autometa -C
```
=> Versioning

modules/local/analyze_kmers.nf, modules/local/binning.nf, modules/local/binning_summary.nf, modules/local/count_kmers.nf, modules/local/embed_kmers.nf, modules/local/get_software_versions.nf, modules/local/hmmer_hmmsearch_filter.nf, modules/local/length_table.nf, modules/local/majority_vote.nf, modules/local/markers.nf, modules/local/normalize_kmers.nf, modules/local/parse_bed.nf, modules/local/prepare_lca.nf, modules/local/reduce_lca.nf, modules/local/spades_kmer_coverage.nf, modules/local/split_kingdoms.nf, modules/local/unclustered_recruitment.nf, workflows/autometa.sh
* :shell::bug: Replace incorrect variable name of `$coverage` with `$coverages` in bash autometa.sh workflow
The `echo "TODO" > autometa.version.txt` within the autometa nextflow processes have been replaced with the recently added `autometa --version` command. This is now being redirected to the retrieved process name as defined by 
```nextflow
def software = getSoftwareName(task.process)
autometa --version | sed "s/autometa: //g" > ${software}.version.txt
```
- The coverages output is assigned the `$coverages` variable, but is called `$coverage` within the `autometa-binning` entrypoint. This has been updated to the appropriate variable (`$coverages`) as defined earlier in the script.
- The autometa version is now emitted at the beginning of the `autometa.sh` workflow with `autometa …
=> :art::green_apple: Add `autometa --version` to autometa nextflow files

.github/CONTRIBUTING.md, docs/source/how-to-contribute.rst, docs/source/index.rst
This PR adds some details to `.github/CONTRIBUTING.md`. Specifically, it outlines how to test code locally through both the bash and nextflow workflows to ensure that local updated code is used. I also made a small change to the documentation - the section previously titled 'Contribution guidelines' is now titles 'How to contribute'. The reason for this is that `.github/CONTRIBUTING.md` contains the contributing guidelines, and the section of the docs is not the same and so having the same title is confusing. Especially as in the first part of that page it suggests looking at the contributing guidelines. A reader is likely to think "aren't I already doing that?".
=> :memo: Added contribution documentation

autometa/validation/cami.py, setup.py
:art: Add CAMI formatter to convert autometa results to [bioboxes specs](https://github.com/bioboxes/rfc/tree/b3b49b111704803e1427c82e2ecf87c5c8ffdfb9/data-format)
The output from this entrypoint formats the respective Autometa results such that they are ready for submission to the CAMI benchmarking tools ([AMBER](https://github.com/CAMI-challenge/AMBER) and [OPAL](https://github.com/CAMI-challenge/OPAL))
```bash
(autometa) evan@userserver:~/Autometa$ autometa-cami-format -h
usage: autometa-cami-format [-h] --sample-predictions SAMPLE_PREDICTIONS --sample-id SAMPLE_ID --results-type {profiling,genome_binning,taxon_binning} [--bioboxes-version BIOBOXES_VERSION] --output OUTPUT
Format Autometa results to biobox format for compatibility with CAMI. Note: All results tables must contain a …
```
=> :art::snake: Add CAMI formatter entrypoint `autometa-cami-format`

docs/source/step-by-step-tutorial.rst
closed old PR and opened new one to merge to dev, issue #304
=> Step by step walkthrough

.github/workflows/docker_autometa.yml, Dockerfile, autometa-env.yml
- Add `schedule: cron: '0 0 * * *'` (i.e. midnight) build for Autometa docker images to catch when builds are failing
- :whale: Explicitly name workdir (`WORKDIR /Autometa`)
- :fire: Remove pinned versions for scipy, scikit-learn and joblib
- :whale: Replace base image with `condaforge/mambaforge`
- 🐎 :whale: Swap `conda` commands with `mamba` commands
=> :fire::whale::green_heart: Fix docker-builds by removing pinned dependencies

Makefile, autometa-env.yml, autometa/binning/recursive_dbscan.py, autometa/binning/unclustered_recruitment.py, docs/source/bash-workflow.rst, docs/source/benchmarking.rst, docs/source/how-to-contribute.rst, docs/source/installation.rst, docs/source/nextflow-workflow.rst, docs/source/step-by-step-tutorial.rst, tests/environment.yml
💚⬆️ Pin `scikit-learn` to `>=1.3`
:snake::art: Replace `conda` commands with `mamba` in `Makefile` 
:fire::arrow_down: Remove `hdbscan` (now available in scikit-learn >= 1.3)
HDBSCAN has been failing in pytests and this seems to be an artifact of hdbscan being integrated into scikit-learn.
Some of these issues have cropped up in the past few weeks (https://github.com/scikit-learn-contrib/hdbscan/issues/600).
scikit-learn is now pinned to >=1.3 as this is the earliest release of HDBSCAN being available via `sklearn.cluster.HDBSCAN`
The `run_hdscan` function has now been updated according to the API that was adopted in the `sklearn` library.
=> 💚:bug::snake: Fix bug for 0 passing predictions

autometa/binning/large_data_mode.py
Remove unnecessary nesting leading to `UnboundLocalError` bug.
Fixes #324
UnboundLocalError resulted from trying to update `binning_checkpoints` dataframe when it was actually not available (occurs when `--cache` is *not* provided). Now variable is initialized accordingly to remove this error.
=> :snake::art::fire::bug: Fix UnboundLocalError bug

docs/requirements.txt
Fixes https://github.com/readthedocs/readthedocs-sphinx-search/security/advisories/GHSA-xgfm-fjx6-62mj
=> :arrow_up: bump readthedocs-sphinx-search; 0.1.1 to 0.3.2

autometa-env.yml, autometa/binning/summary.py, autometa/common/metagenome.py, tests/unit_tests/test_metagenome.py
- Fixes pandas version to `>=1.5`. 
- Fixes issue #350
=> Fix Issue#350
